@url = https://spice.danielherlev.dk/api/users/

@jwt_token = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJNb2xkYSIsInN1YiI6Im1pbmdvIiwiZXhwIjoxNzM0NTE3NzY2LCJyb2xlcyI6IkFETUlOIiwidXNlcm5hbWUiOiJtaW5nbyJ9.Ia-Q75OZvP8SMSU4lGwDV1VyVDK-dwprVETK2dJMfyo
###
GET {{url}}