@url = https://spice.danielherlev.dk/api/users

@jwt_token = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJNb2xkYSIsInN1YiI6Im1pbmdvIiwiZXhwIjoxNzM0NTE3NzA2LCJyb2xlcyI6IkFETUlOIiwidXNlcm5hbWUiOiJtaW5nbyJ9.XyG3qte_ZUsMWNT98C5MHQWvJJ6Y4F5QXSnhYFbP14E
GET {{url}}