@url = https://spice.danielherlev.dk/api/spices

@jwt_token = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJKb24gQmVydGVsc2VuIiwic3ViIjoidXNlciIsImV4cCI6MTczMzU5NzIzNiwicm9sZXMiOiJVU0VSIiwidXNlcm5hbWUiOiJ1c2VyIn0.Lr2tqkRjjmvHDCmcpxkP3_mFwCCFcXeFOF4i3Kda1oI

###
GET {{url}}